### ISSUE TITLE
Parametrizable shortcut actions (inputs and outputs intents)

### ISSUE THREAD

**Issue by marioshtika** [lovetodream/capacitor-plugin-siri-shortcuts#1]
Is there a way to run parametrizable shortcut actions?
To give inputs or/and get outputs from an action?

Something like this:
![parametrizable-shortcut-actions](https://user-images.githubusercontent.com/3079663/102263307-cadc4700-3f1c-11eb-92a3-2c87946dc952.png)

**Comment by TimoZacherl** [comment]
There is no straight forward way to implement this.
You can provide inputs inside your Capacitor App and donate the pre-configured shortcut to Siri.

Nevertheless I will have a look, if something like that might be possible with the current way I've created this plugin and without having to create to much native code on your own.

**Comment by marioshtika** [comment]
Thank you very much, for your response.
The ideal solution would be the inputs would run through a function on an existing service.
But may be, another more simple solution would be sending those inputs to an external endpoint.

**Comment by TimoZacherl** [comment]
I didn't find any other way then using Siri Intents, which would be very specific to the app they are used in. Furthermore I couldn't find any way to use Capacitor/Ionic for creating these in a straight forward way. 
Therefor I am sorry, but I cannot implement this into the plugin at the moment, because I don't see a clear solution and I don't have much time for this project at the moment.
If you have time and the expertise to implement this feel free to create a PR.

**Comment by ahmedelrefaiy** [comment]
Is it resolved? i search for a solution for that and i find nothing!
