### ISSUE TITLE
Show siri shortcuts in Shortcuts app

### ISSUE THREAD

**Issue by tylerclark** [lovetodream/capacitor-plugin-siri-shortcuts#53]
So far, I am able to create shortcuts by donating and presenting the shortcut. However, this requires the user to accept a dialog. I would like my app's shortcuts to appear automatically, just like the native ChatGPT app's shortcuts.

To achieve this, I have added the Siri capability and added the following lines to my Info.plist file:
```
<key>NSUserActivityTypes</key>
    <array>
      <string>com.umbrella.vet.shortcut</string>
      <string>AskUmbrellaIntent</string>
    </array>
```

I am also calling donate on mount:
```
await SiriShortcuts.donate({
  persistentIdentifier: 'com.umbrella.vet.shortcut',
  title: 'Ask Umbrella Intent',
  suggestedInvocationPhrase: 'Ask Umbrella',
  isEligibleForSearch: true,
  isEligibleForPrediction: true,
})
```

I have a folder called Intents with one intent named AskUmbrellaIntent, and an Intents.intentdefinition file.

However, I cannot see my shortcuts in the Shortcuts app. It's probably a naming thing but what am I missing?

**Comment by lovetodream** [comment]
Sorry for the late reply. It seems like you're trying to donate an Intent, which unfortunately isn't supported by this plugin. This is the case, because Intents can't be handled without specific Swift/Obj-C code for each Intent Definition. So it not really suitable as a general purpose plugin. You'd either need to create a specific plugin for your use case or use the basic shortcuts/activities the plugin can handle.

Please be aware that Donations do not create Shortcuts directly, they only provide Actions to the Shortcuts app, which in turn can be used within Shortcuts your users are creating. If they don't appear inside Actions it could be due to the App running on a Simulator, which sometimes doesn't work for whatever reason.

I'm no longer using the Plugin myself, but if you have any other questions, just let me know.
